export enum EEventName {
    MESSAGE = "MESSAGE",
    MESSAGE_DONE = "MESSAGE_DONE",
    HERO_POSITION = "HERO_POSITION",
    OBJECT_MOVE_COMPLETED = "OBJECT_MOVE_COMPLETED",
    OBJECT_STAND_COMPLETED = "OBJECT_STAND_COMPLETED",

    MAP_TRANSITION_START = "MAP_TRANSITION_START",
    MAP_TRANSITION_END = "MAP_TRANSITION_END",

    OPEN_IFRAME = "OPEN_IFRAME",
    CLOSE_IFRAME = "CLOSE_IFRAME",
}
